### PR TITLE
Problem: Blending tests in the mapping branch should pass.

### PR DESCRIPTION
**Pull request by kegor**
**Problem:**
This PR contains changes for fixing the Blending tests in the `mapping` branch, originally from https://github.com/Starcounter/Blending/issues/69#issue-295083517.

**Solution:** 
- Empty blend.json files were added into the pair of test helper apps.
- Select query in DataHelper was rewritten.
- References to the `Simplified` were removed.

**Tests:**
Passed: https://teamcity.starcounter.org/viewLog.html?buildId=58286&tab=buildResultsDiv&buildTypeId=Apps_Blending_BlendingMasterWithStarcounterDevelop24.

### CODE REVIEW

**Comment by PatrykSzwer** [comment]
BTW could you also remove commented code from here before you merge? https://github.com/Starcounter/Blending/blob/mapping/src/BlendingEditor/Website/Helpers/MigrationHelper.cs#L67
I forgot to delete it when I was changing stardump based migration to the json based one.

**Comment by kegor** [comment]
Hi @PatrykSzwer, I definitely need to explain this trick with the empty blend.json files:
I found that the problem like this `System.ArgumentException: The following URI is already added to blender: "/blendingeditor/app-name" on token "JustEmptyToken"` here https://teamcity.starcounter.org/viewLog.html?buildId=58153&buildTypeId=Apps_Blending_BlendingMasterWithStarcounterDevelop24&tab=buildLog

I think because `BlendingEditor_TestHelper` copying the `blend.json` from the `BlendingEditor` debug folder because it has the reference on the BE project and because `blend.json` has property copy local.
The problem here is that when `BlenderEditor_TestHelper` starts the `Blender` class trying to create attaching rules from the copied `blend.json` file again.

By adding empty `blend.json` files into the pair of the test projects I overrided this behaviour.

**Comment by PatrykSzwer** [comment]
I think it should be either reported or documented somewhere, but I'm not sure where. @warpech do u have some opinion about it?

**Comment by warpech** [comment]
Is it required for `blend.json` to have property copy local? Maybe it has to be fixed in our `csproj`, not documented? If you think it deserves further discussion, pls make an issue

**Pull request merged**
