### PR TITLE
Problem #137: warning for a user if he trying to save Layout Condition with empty URI.

### PR DESCRIPTION
**Pull request by kegor**
**Problem #137:**
 Will be good to warn a user if he trying to save Layout Condition with empty URI.

**Solution:**
The warning that is triggered on back-end was added.

**Tests:**
✅ The manual check was successful.

**Screenshots:**
warning_for_layoutcondition_with_empty_uri

### CODE REVIEW

**Comment by un-tone** [comment]
I guess, it is not enough to just warn, preventing is better for this case. Otherwise, the layout condition is saved and if a user will go to any other page, i.e. "General" he still gets an empty page and he will be able to do nothing with it. It will be a big problem for the user if he had some working settings there.

**Comment by un-tone** [comment]
I should note that a user is getting an empty page only in case if a user added a condition for newly added layout. I propose to implement additional checkings to prevent adding such breaking data.

**Comment by warpech** [comment]
I agree with @un-tone that this needs changes. I will propose a different UX design for it.

**Comment by warpech** [comment]
I added my proposal of changes to https://github.com/Starcounter/Blending/issues/137#issuecomment-377930123.

If you agree then I think this PR should be closed and a new one is needed.

Big thanks for being proactive in proposing such solutions, anyway!

**Comment by kegor** [comment]
Closed because we decided to improve UX of the Layout Conditions page https://github.com/Starcounter/Blending/issues/137#issuecomment-377930123. And the implementation of the warning will change.

**Pull request closed without merging**
