### PR TITLE
Merge starcounter-layout-html-editor into BlendingEditor

### PR DESCRIPTION
**Pull request by warpech**
`starcounter-layout-html-editor` was moved from `/sys` to `/BlendingEditor/elements`.

Required packages were moved to the BlendingEditor's `bower.json`

@tomalec could you pls help me out with setting up Travis CI?

### CODE REVIEW

**Comment by tomalec** [comment]
It would be nicer to move `starcounter-layout-html-editor` in a single commit, so git could track it, as it's deleted in one, and added in second it's hard to track the changes in files.

**Comment by tomalec** [comment]
Created a branch to visualize what I mean https://github.com/Starcounter/Blending/compare/merge_starcounter-layout-html-editor-2?expand=1

**Comment by tomalec** [comment]
We, need to update paths to custom element in BlendingEditor views.

**Comment by warpech** [comment]
> It would be nicer to move starcounter-layout-html-editor in a single commit, so git could track it, as it's deleted in one, and added in second it's hard to track the changes in files.

Ooops, that was actually my intention! It seems that I forgot to stage half of the files. Can you pls make a PR from your branch? I will close this one then

**Comment by warpech** [comment]
This PR should be closed, as it continues in another PR https://github.com/Starcounter/Blending/pull/341

**Pull request closed without merging**
