### PR TITLE
17 drag and drop routes

### PR DESCRIPTION
**Pull request by alshakero**
I used ordering buttons, they're easy to reason about, easy to implement and don't require any libs. Albeit I agree DnD can be more satisfying.

Fixes: https://github.com/Starcounter/Blending/issues/17

### CODE REVIEW

**Comment by warpech** [comment]
As we discussed on the today's meeting, there is value in drag and drop. @alshakero will try again looking how https://codetree.com/ implemented drag and drop of a `<tr>`.

**Comment by alshakero** [comment]
Readt for review. It works on Chrome, FF and Edge.

**Comment by PatrykSzwer** [comment]
I would also experiment a little with different icon for drag. Something more like this maybe: 
image


or I think most common ways, couple of grey dots, like here:
image

**Comment by alshakero** [comment]
Can you continue on your suggestions now that the DnD annoying part is done?

**Comment by PatrykSzwer** [comment]
I fixed the logical part of the functionality. There is still some problem with "jumping" table, @alshakero could you take a look?
rep

**Comment by alshakero** [comment]
@PatrykSzwer should be done.

**Comment by PatrykSzwer** [comment]
There were some problems caused by newest changes in SC which I fixed in last commit, but turns out that there is still some problem with proper order setting with drag and drop:
rep

**Comment by PatrykSzwer** [comment]
All the backend part of this feature should be working fine. Only thing left is to get keys of drag and drop items properly, after table was changed in same transaction. @alshakero will continue work on this issue.

**Comment by warpech** [comment]
On today's meeting @alshakero suggested that the algorithm needs some more work. @kegor will take the C# part.

**Comment by tomalec** [comment]
It seems we are almost there, but it's hard to debug it given https://github.com/Starcounter/Home/issues/121#issuecomment-376512275

Let's wait with further work, until we can actually inspect anything in VS.

**Comment by PatrykSzwer** [comment]
I've fixed drag and drop feature for all layout conditions view. Please check if it works without any issues.

I talked with @warpech and we decided to, for now, drop ordering feature for specific layout view. This issue took already too much time and contains wide, conflictable changes that should be merged. 

@alshakero please take a final look and merge if you decide that It's working without any issues.

**Comment by alshakero** [comment]
Works like a charm!

**Comment by alshakero** [comment]
Any idea why tests are failing?

**Comment by kegor** [comment]
@alshakero seems like in latest run tests was successful again, but I'm looking at this situation today.

**Pull request merged**
